-- Sample mystery packages for development
INSERT INTO mystery_packages (id, title, description, image_url, price, currency, duration_minutes, min_players, max_players, difficulty, themes, plot_summary, is_available, created_at, updated_at) VALUES
('550e8400-e29b-41d4-a716-446655440001', 'Murder and Dragons', 'A fantasy-themed murder mystery where players must solve the murder of a powerful sorcerer at a magical academy.', 'https://example.com/castle.jpg', 29.99, 'USD', 120, 6, 20, 'MEDIUM', '{"Fantasy", "Political Intrigue"}', 'In the enchanted kingdom of Eldoria, the Grand Sorcerer has been found murdered in his tower. As investigators from the Magical Council, players must navigate court politics, magical artifacts, and ancient rivalries to uncover the truth.', true, '2024-01-15T10:30:00Z', '2024-01-15T10:30:00Z'),
('550e8400-e29b-41d4-a716-446655440002', 'Murder at the School of Witchcraft and Wizardry', 'A magical academy mystery with young wizards, enchanted artifacts, and dark secrets.', 'https://example.com/wizard-duel.jpg', 19.99, 'USD', 120, 6, 16, 'EASY', '{"Fantasy", "Pop Culture"}', 'At the prestigious Hogwarts-style academy, the headmaster has been poisoned during the annual feast. Students and staff must investigate magical mishaps, forbidden spells, and hidden grudges.', true, '2024-01-15T10:30:00Z', '2024-01-15T10:30:00Z'),
('550e8400-e29b-41d4-a716-446655440003', 'Murder at a Board Game Night', 'A meta murder mystery that breaks the fourth wall with game references and player interaction.', 'https://example.com/mansion.jpg', 19.99, 'USD', 120, 10, 24, 'MEDIUM', '{"Humorous", "Meta"}', 'During what should have been a friendly board game night, the host is found murdered. Players must navigate game mechanics, player personalities, and meta-narratives to solve the crime.', true, '2024-01-15T10:30:00Z', '2024-01-15T10:30:00Z');

-- Sample characters for first mystery package
INSERT INTO character_templates (mystery_package_id, name, description, avatar_url, role, background, personality, objectives, secrets) VALUES
('550e8400-e29b-41d4-a716-446655440001', 'Elara Shadowbane', 'A cunning elf sorceress with a mysterious past.', 'https://example.com/elf.jpg', 'SUSPECT', 'Elara is a master of shadow magic who graduated from the academy 10 years ago. She has been traveling the realms, collecting rare artifacts.', 'Ambitious and secretive, Elara is always calculating her next move. She speaks in riddles and has a habit of disappearing when questions get too personal.', '{"Discover the truth about the sorcerer''s death", "Protect the academy''s secrets"}', '{"Elara was secretly in love with the sorcerer", "She stole a forbidden artifact from the academy''s vault"}'),
('550e8400-e29b-41d4-a716-446655440001', 'Thrain Ironfist', 'A dwarven blacksmith known for his craftsmanship and temper.', 'https://example.com/dwarf.jpg', 'SUSPECT', 'Thrain has been the academy''s blacksmith for 30 years. His weapons and armor are legendary throughout the kingdom.', 'Gruff and straightforward, Thrain has little patience for "fancy magic" and believes in hard work and honesty. He''s quick to anger but has a soft spot for apprentices.', '{"Find out who killed his friend the sorcerer", "Ensure the academy remains a place of learning"}', '{"Thrain was being blackmailed by the sorcerer", "He forged a weapon that was used in the murder"}'),
('550e8400-e29b-41d4-a716-446655440001', 'Detective Mira Voss', 'A human detective from the capital city, known for solving impossible cases.', 'https://example.com/detective.jpg', 'DETECTIVE', 'Mira has solved over 50 murder cases in her career. She was personally requested by the king to investigate this sensitive matter.', 'Sharp-witted and methodical, Mira has an uncanny ability to notice details others miss. She''s professional but has a dry sense of humor.', '{"Solve the murder and bring the culprit to justice", "Maintain order in the magical community"}', '{"Mira has magical abilities she keeps hidden", "She has a personal connection to the academy"}');

-- Sample game phases for first mystery package
INSERT INTO game_phases (mystery_package_id, name, description, order_index, duration_minutes, instructions, host_instructions, is_interactive, requires_host_action) VALUES
('550e8400-e29b-41d4-a716-446655440001', 'The Discovery', 'The body is discovered and initial shock sets in.', 1, 15, '{"Gather in the main hall", "Listen to the host''s announcement", "Begin asking initial questions"}', '{"Describe the scene dramatically", "Distribute initial clues", "Answer questions about the academy"}', false, true),
('550e8400-e29b-41d4-a716-446655440001', 'Individual Investigations', 'Players split up to investigate different areas of the academy.', 2, 30, '{"Form small investigation groups", "Visit assigned locations", "Collect clues and interview suspects"}', '{"Guide players to different areas", "Provide location-specific clues", "Facilitate role-playing interactions"}', true, false),
('550e8400-e29b-41d4-a716-446655440001', 'The Accusation', 'Players gather evidence and make accusations.', 3, 45, '{"Present findings to the group", "Vote on suspects", "Defend your theories"}', '{"Moderate the discussion", "Reveal additional evidence based on progress", "Build tension and suspense"}', true, true),
('550e8400-e29b-41d4-a716-446655440001', 'The Resolution', 'The truth is revealed and the mystery is solved.', 4, 30, '{"Listen to the final revelation", "Discuss what you learned", "Reflect on the experience"}', '{"Reveal the full story", "Explain any remaining mysteries", "Facilitate post-game discussion"}', false, true);
